// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jndlesmoploedovmclda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZGxlc21vcGxvZWRvdm1jbGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDcwNjgsImV4cCI6MjA2MTUyMzA2OH0.Y09TvEvcrIMbvWCFdo_iGafFWwKHPvlxdbcchyf1LV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);